name: station_reach
description: "See where transit takes you!"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0-333.2.beta

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.1
  fpdart: ^1.1.1
  get_it: ^8.2.0
  go_router: ^16.2.0
  webfabrik_theme:
    git: https://github.com/ton-An/webfabrik_theme
  intl: ^0.20.2
  equatable: ^2.0.7
  dio: ^5.9.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  flutter_map: ^8.2.1
  shimmer_animation: ^2.2.2
  collection: ^1.19.1
  latlong2: ^0.9.1
  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
  
flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_variable.ttf
