name: station_reach
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.1
  fpdart: ^1.1.1
  get_it: ^8.2.0
  go_router: ^16.2.0
  maplibre: ^0.2.2
  webfabrik_theme:
    git: https://github.com/ton-An/webfabrik_theme
  intl: ^0.20.2
  equatable: ^2.0.7
  dio: ^5.9.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  pointer_interceptor: ^0.10.1+2
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_variable.ttf
